{% set name = "mgnify-pipelines-toolkit" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mgnify_pipelines_toolkit-{{ version }}.tar.gz
  sha256: 8c4593be90d8f4bf07d8b8998ba3fd9c0bfb159edda2bcf3fb741a81c6554c3f

build:
  entry_points:
    - get_subunits = mgnify_pipelines_toolkit.v6.get_subunits:main
    - get_subunits_coords = mgnify_pipelines_toolkit.v6.get_subunits_coords:main
    - mapseq2biom = mgnify_pipelines_toolkit.v6.mapseq2biom:main
    - are_there_primers = mgnify_pipelines_toolkit.v6.v6_amplicon.are_there_primers:main
    - assess_inflection_point_mcp = mgnify_pipelines_toolkit.v6.v6_amplicon.assess_inflection_point_mcp:main
    - assess_mcp_proportions = mgnify_pipelines_toolkit.v6.v6_amplicon.assess_mcp_proportions:main
    - classify_var_regions = mgnify_pipelines_toolkit.v6.v6_amplicon.classify_var_regions:main
    - find_mcp_inflection_points = mgnify_pipelines_toolkit.v6.v6_amplicon.find_mcp_inflection_points:main
    - make_asv_count_table = mgnify_pipelines_toolkit.v6.v6_amplicon.make_asv_count_table:main
    - remove_ambiguous_reads = mgnify_pipelines_toolkit.v6.v6_amplicon.remove_ambiguous_reads:main
    - rev_comp_se_primers = mgnify_pipelines_toolkit.v6.v6_amplicon.rev_comp_se_primers:main
    - standard_primer_agrep = mgnify_pipelines_toolkit.v6.v6_amplicon.standard_primer_agrep:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - biopython ==1.81
    - numpy ==1.24.3
    - pandas ==2.0.2

test:
  imports:
    - mgnify_pipelines_toolkit
  commands:
    - pip check
    - get_subunits --help
    - get_subunits_coords --help
    - mapseq2biom --help
    - are_there_primers --help
    - assess_inflection_point_mcp --help
    - assess_mcp_proportions --help
    - classify_var_regions --help
    - find_mcp_inflection_points --help
    - make_asv_count_table --help
    - remove_ambiguous_reads --help
    - rev_comp_se_primers --help
    - standard_primer_agrep --help
  requires:
    - pip

about:
  summary: Collection of scripts and tools for MGnify pipelines
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisAta
